name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create source archive
        run: zip -r reactopus-source.zip . -x "node_modules/*" ".git/*" ".github/*" "*.js"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "reactopus.min.js,reactopus-source.zip"
          tag: v${{ github.run_number }}
          allowUpdates: true
